name: Run Tests
run-name: Testing the Project
on: [push]
jobs:
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check Python Version
        run: python3 --version
      - name: Running tests
        run: |
          pip install pipenv
          pipenv install
          pipenv run tests
