name: Run Tests
run-name: Testing the Project
on: [push]
jobs:
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 qt5-default libqt5x11extras5
      - name: Running tests
        run: |
          pip install pipenv
          pipenv install
          xvfb-run --auto-servernum pipenv run tests
