name: Run Tests
run-name: Testing the Project
on: [push]
jobs:
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xsel python3-tk xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libqt5x11extras5 qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools
      - name: Initialize clipboard
        run: |
          export DISPLAY=:99
          export XDG_SESSION_TYPE=x11
          # Start Xvfb in the background
          Xvfb :99 -screen 0 1024x768x16 &
          sleep 1 # Wait for Xvfb to start
          # Initialize the clipboard by setting a dummy value
          echo "initialize" | xsel --clipboard --input
      - name: Running tests
        run: |
          pip install pipenv
          pipenv install
          XDG_SESSION_TYPE=x11 xvfb-run --auto-servernum pipenv run tests
